# Generated by Django 5.0.1 on 2024-02-24 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel_management_system", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hotelprofile",
            name="approved",
        ),
        migrations.AddField(
            model_name="user",
            name="approved",
            field=models.BooleanField(default=False),
        ),
    ]
